name: to_do_list_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.17.0
  google_fonts: ^4.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.0
  flutter_slidable: ^3.0.0
  animated_text_kit: ^4.2.2
  lottie: ^3.1.3
  shared_preferences: ^2.3.2
  # awesome_notifications: ^0.7.4+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/New notifications.gif
    - assets/images/Profile Interface.gif
    - assets/images/Mobile inbox.gif
    - assets/images/active_task.png
    - assets/images/tasks.png
    - assets/images/5orang.jpg
    - assets/images/searchicon.png




